before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - main: ./cmd/silo
    binary: silo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/eternisai/silo/internal/cli.version={{.Version}}
      - -X github.com/eternisai/silo/internal/cli.commit={{.Commit}}
      - -X github.com/eternisai/silo/internal/cli.buildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
